name: DockerHUb CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  docker:
    runs-on: self-hosted
    
    container: docker
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Test Image
        run: docker build . --file tests.Dockerfile --tag devops-training-flask-app-tests:latest

      - name: Build Test Image
        run: docker run devops-training-flask-app-tests:latest
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: prod.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-training-flask-app-tests:latest
  
